import assert from "node:assert/strict";
import {
	isAutoGeneratedSessionLabel,
	titleFromUserText,
	firstUserMessageFromJsonlLines,
} from "../../session-label.ts";

assert.equal(isAutoGeneratedSessionLabel("2026-07-08T12:00:00", "abc"), true);
assert.equal(isAutoGeneratedSessionLabel("我的任务", "abc"), false);
assert.equal(titleFromUserText("  hello world  "), "hello world");
const line = JSON.stringify({
	kind: "pi_event",
	eventName: "input",
	detail: { text: "整理项目根目录" },
	summary: "input … (user)",
});
assert.equal(firstUserMessageFromJsonlLines([line]), "整理项目根目录");
console.log("session-label.test.mjs: ok");