import { appendFileSync, existsSync, mkdirSync } from "node:fs";
import { getActiveSession } from "./session-context.js";
import {
	isAutoGeneratedSessionLabel,
	pickSessionDisplayLabel,
	titleFromUserText,
} from "./session-label.js";
import { sessionLogPath, touchSessionInRegistry } from "./session-registry.js";
import type { StreamSnapshot } from "./stream-result.js";
import type { UsageMetrics } from "./usage-metrics.js";
import { isObservationDualWriteEnabled, observationTraceLine } from "./observability/write-observation.js";

export type TraceKind =
	| "request"
	| "response_meta"
	| "stream_update"
	| "stream_result"
	| "sse_line"
	| "error"
	| "pi_event"
	| "llm_usage"
	| "observation";

export type TraceRecord = {
	ts: string;
	kind: TraceKind;
	id: string;
	sessionKey?: string;
	sessionLabel?: string;
	url?: string;
	method?: string;
	status?: number;
	headers?: Record<string, string>;
	bodyPreview?: string;
	/** Legacy live-only field. New captures emit stream_update snapshots instead. */
	line?: string;
	stream?: StreamSnapshot;
	/** Text-only patch for a live update; the logger folds it into its in-memory snapshot. */
	streamDelta?: { text?: string; reasoning?: string };
	message?: string;
	eventName?: string;
	summary?: string;
	detail?: Record<string, unknown>;
	usage?: UsageMetrics;
};

let logDir: string | null = null;
let enabled = false;
const listeners = new Set<(record: TraceRecord) => void>();
const liveStreams = new Map<string, TraceRecord>();
const lastRegistryTouch = new Map<string, number>();
const REGISTRY_TOUCH_MS = 2500;

function liveKey(record: TraceRecord): string {
	return `${record.sessionKey ?? "unknown"}:${record.id}`;
}

function isLiveOnly(record: TraceRecord): boolean {
	return record.kind === "stream_update" || record.kind === "sse_line";
}

function mergeLiveStreamRecord(record: TraceRecord): TraceRecord {
	if (!record.streamDelta || !record.stream) return record;
	const previous = liveStreams.get(liveKey(record))?.stream;
	return {
		...record,
		stream: {
			...previous,
			...record.stream,
			text: (previous?.text ?? "") + (record.streamDelta.text ?? ""),
			reasoning: (previous?.reasoning ?? "") + (record.streamDelta.reasoning ?? ""),
		},
		streamDelta: undefined,
	};
}

export function setTraceLogDir(dir: string): void {
	logDir = dir;
	if (!existsSync(dir)) mkdirSync(dir, { recursive: true });
}

export function setTraceEnabled(on: boolean): void {
	enabled = on;
	if (!on) liveStreams.clear();
}

export function isTraceEnabled(): boolean {
	return enabled;
}

export function getTraceLogDir(): string | null {
	return logDir;
}

export function subscribeTrace(listener: (record: TraceRecord) => void): () => void {
	listeners.add(listener);
	return () => listeners.delete(listener);
}

/** Latest cumulative snapshots for streams that have not produced a final result yet. */
export function listLiveTraceRecords(sessionKey?: string): TraceRecord[] {
	return [...liveStreams.values()]
		.filter((record) => !sessionKey || record.sessionKey === sessionKey)
		.sort((a, b) => a.ts.localeCompare(b.ts));
}

export function getHttpSseLogPath(sessionKey?: string): string | null {
	if (!logDir) return null;
	const key = sessionKey ?? getActiveSession().key;
	return sessionLogPath(logDir, key);
}

const SENSITIVE_HEADER = /^(authorization|x-api-key|api-key|cookie)$/i;

export function redactHeaders(headers: Headers | Record<string, string>): Record<string, string> {
	const out: Record<string, string> = {};
	if (headers instanceof Headers) {
		headers.forEach((value, key) => {
			out[key] = SENSITIVE_HEADER.test(key) ? "[redacted]" : value;
		});
		return out;
	}
	for (const [key, value] of Object.entries(headers)) {
		out[key] = SENSITIVE_HEADER.test(key) ? "[redacted]" : value;
	}
	return out;
}

export function previewBody(body: unknown, max = 200_000): string | undefined {
	if (body == null) return undefined;
	if (typeof body === "string") {
		return body.length > max ? body.slice(0, max) + "…[truncated]" : body;
	}
	if (body instanceof URLSearchParams) return body.toString();
	if (body instanceof ArrayBuffer) return `[ArrayBuffer ${body.byteLength}]`;
	if (ArrayBuffer.isView(body)) return `[Binary ${body.byteLength}]`;
	if (typeof (body as ReadableStream).getReader === "function") return "[ReadableStream]";
	try {
		const value = JSON.stringify(body);
		return value.length > max ? value.slice(0, max) + "…[truncated]" : value;
	} catch {
		return `[${Object.prototype.toString.call(body)}]`;
	}
}

function enrichRecord(record: TraceRecord): TraceRecord {
	const active = getActiveSession();
	let sessionLabel = record.sessionLabel ?? active.label;
	if (
		record.kind === "pi_event" &&
		record.eventName === "input" &&
		typeof record.detail?.text === "string"
	) {
		const title = titleFromUserText(record.detail.text);
		if (title && isAutoGeneratedSessionLabel(sessionLabel, active.key)) sessionLabel = title;
	}
	return {
		...record,
		sessionKey: record.sessionKey ?? active.key,
		sessionLabel,
	};
}

function appendDurableRecord(record: TraceRecord): void {
	if (!logDir || !record.sessionKey) return;
	try {
		const path = sessionLogPath(logDir, record.sessionKey);
		appendFileSync(path, `${JSON.stringify(record)}\n`, "utf8");
	} catch {
		// Tracing must never break the model request.
	}
}

function updateRegistry(record: TraceRecord): void {
	if (!logDir || !record.sessionKey || isLiveOnly(record)) return;
	const now = Date.now();
	const last = lastRegistryTouch.get(record.sessionKey) ?? 0;
	if (now - last < REGISTRY_TOUCH_MS) return;
	lastRegistryTouch.set(record.sessionKey, now);
	const label = pickSessionDisplayLabel({ key: record.sessionKey, label: record.sessionLabel });
	touchSessionInRegistry(logDir, record.sessionKey, label, record.ts);
}

function publish(record: TraceRecord): void {
	for (const listener of listeners) {
		try {
			listener(record);
		} catch {
			// One faulty UI subscriber must not affect tracing.
		}
	}
}

/**
 * Persists durable facts and publishes transient stream snapshots.
 * `stream_update` and legacy `sse_line` records are memory-only by contract.
 */
export function writeTrace(record: TraceRecord): void {
	if (!enabled || !logDir) return;
	const full = enrichRecord(record);
	const key = liveKey(full);

	if (full.kind === "stream_update") liveStreams.set(key, mergeLiveStreamRecord(full));
	if (full.kind === "stream_result") liveStreams.delete(key);

	if (!isLiveOnly(full)) {
		appendDurableRecord(full);
		if (isObservationDualWriteEnabled() && full.kind === "llm_usage") {
			const observation = observationTraceLine(full);
			if (observation) appendDurableRecord(enrichRecord(observation));
		}
	}

	updateRegistry(full);
	publish(full);
}

export function _resetTraceWriteStateForTests(): void {
	liveStreams.clear();
	lastRegistryTouch.clear();
}
